### ISSUE TITLE
Getting 401 errors

### ISSUE THREAD

**Issue by rastrau** [ernstbaslerpartner/walkalytics-clients#2]
I receive an "HTTP Error 401: Access Denied" upon invoking Isochrone or IsochroneRaw using ArcGIS for desktop both with the primary key of a *Starter Walkalytics* as well as *Unlimited Walkalytics* product from https://dev.walkalytics.com/developer. 
The state of both subscriptions is 'Active' and renewing the key did not amend the situation.
What might I be doing wrong?

**Comment by ping13** [comment]
Okay, the API key was not recognized, if it was given in the UI dialog box (instead of the parameter file).
