### ISSUE TITLE
Suggestion: Informative names for ASCII output files of Python client

### ISSUE THREAD

**Issue by rastrau** [ernstbaslerpartner/walkalytics-clients#4]
Currently, the zipped ASCII output files have informative names, such as: `isochrone_944090_6009149.asc.gz`. However, unzipping them uniformly produces a file `output.asc`. 

For convenience it would be nice to have the unzipped files to have informative names as well (especially useful for batch-processing of numerous POIs).

**Comment by ping13** [comment]
fixed with https://github.com/ernstbaslerpartner/walktime/commit/58287e70b0e71399d8a30cb5d5c751c33d808d67
